#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

PAYLOAD=$(mktemp /tmp/resource-check.XXXXXX)

cat > "$PAYLOAD" <&0

# Always return a new version being available to ensure the
# job is run without using the cache.
# Returns the previous version if passed in.

THIS_TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
LAST_TIMESTAMP="$(jq -r '.version.timestamp // empty' < "$PAYLOAD")"

if [ -z "$LAST_TIMESTAMP" ]; then
  jq -n "[ { timestamp: \"$THIS_TIMESTAMP\" } ]" >&3
else
  jq -n "[ { timestamp: \"$LAST_TIMESTAMP\" },
           { timestamp: \"$THIS_TIMESTAMP\" } ]" >&3
fi
