#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

BASE_DIR=$(dirname "$0")
DEST_DIR=$1
PAYLOAD=$(mktemp /tmp/resource-in.XXXXXX)
TIMESTAMP=$(date '+%Y%m%d_%H%M%S')

cat > "$PAYLOAD" <&0

ENGINE=$(jq -r '.source.engine' < "$PAYLOAD")
ENGINE_FILE=$BASE_DIR/engines/$ENGINE

if [ ! -e "$ENGINE_FILE" ]; then
  echo "Database $ENGINE not supported (file not found: $ENGINE_FILE)"
  exit 1
fi

"$ENGINE_FILE" "$PAYLOAD" "$DEST_DIR" "$TIMESTAMP" || exit 1

FILES=$(find "$DEST_DIR" -mindepth 1 -type f -printf '%f (%k KiB)\0' | jq -Rr 'split("\u0000")|join("\n")')

jq -n "{
  version: {
    timestamp: \"$TIMESTAMP\"
  },
  metadata: [
    { name: \"File\", value: \"$FILES\" }
  ]
}" >&3
